//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnixLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutinas
    {
        public int IdRutina { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idEjercicio { get; set; }
        public string NombreRutina { get; set; }
        public Nullable<int> idEjercicioRutina { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual EjercicioRutina EjercicioRutina { get; set; }
    }
}
